#!/bin/sh

FILE=logo.txt
LOOP=10

function INIT {
	echo -e "\033[2J"
	echo -e "\033[1;1f"
}

function CURSOR_DOWN {
	echo -en "\033[${1}B"
}
function CURSOR_FORWARD {
	echo -en "\033[${1}C"
}


function COLOR_YELLOW_BACKGROUND {
	echo -en "\033[43m"
}
function COLOR_BLACK_BACKGROUND {
	echo -en "\033[40m"
}
function COLOR_WHITE_BACKGROUND {
	echo -en "\033[47m"
}
function COLOR_DEFAULT {
	echo -en "\033[0m"
}

OLD_IFS=$IFS
IFS=""
while [ $LOOP -ge 0 ]
do
	INIT

	Y=0
	while read LINE
	do
		X=$LOOP
		CURSOR_FORWARD $X
		echo "$LINE" | while read -N 1 CHAR
		do
      if [ "x$CHAR" = "x " ]
			then
				COLOR_YELLOW_BACKGROUND
				echo -n " "
      elif [ "x$CHAR" = "x@" ]
      then
				COLOR_BLACK_BACKGROUND
				echo -n " "
      elif [ "x$CHAR" = "x8" ]
      then
				COLOR_WHITE_BACKGROUND
				echo -n " "
			else
				echo -n "$CHAR"
			fi

			X=$(($X + 1))
		done
		Y=$(($Y + 1))
	done < $FILE

	LOOP=$(($LOOP - 1))
	COLOR_DEFAULT
  sleep 0.2
done

IFS=$OLD_IFS

exit 0
